# Generated by Django 4.1.4 on 2022-12-28 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PetrolType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="car",
            name="petrol",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="rental.petroltype",
            ),
            preserve_default=False,
        ),
    ]
