# Generated by Django 4.1.4 on 2022-12-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0002_petroltype_car_petrol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="image",
            field=models.ImageField(upload_to="rental/static/rental/car_images"),
        ),
    ]
