# Generated by Django 4.1.4 on 2022-12-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0003_alter_car_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="price",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
