# Generated by Django 4.1.4 on 2023-01-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rental", "0004_car_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="seats",
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
