# Generated by Django 4.1.5 on 2023-01-07 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rental", "0005_car_seats"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rental",
            name="description",
        ),
        migrations.RemoveField(
            model_name="rental",
            name="price",
        ),
        migrations.AddField(
            model_name="rental",
            name="endDate",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rental",
            name="name",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rental",
            name="phoneNumber",
            field=models.CharField(default=123123123, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rental",
            name="startDate",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rental",
            name="surname",
            field=models.CharField(default="Test", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rental",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
